export const permissions = {
  1: [
    { dataapproval_view_permission: 'dataapproval.view.permission' },
    { dataapproval_add_permission: 'dataapproval.add.permission' },
    { dataapproval_edit_permission: 'dataapproval.edit.permission' },
    { dataapproval_delete_permission: 'dataapproval.delete.permission' },
    { dataapproval_accept_permission: 'dataapproval.accept.permission' },
    { indicatorcategory_view_permission: 'indicatorcategory.view.permission' },
    { indicatorcategory_add_permission: 'indicatorcategory.add.permission' },
    { indicatorcategory_edit_permission: 'indicatorcategory.edit.permission' },
    {
      indicatorcategory_delete_permission:
        'indicatorcategory.delete.permission',
    },
    {
      indicatorcategory_accept_permission:
        'indicatorcategory.accept.permission',
    },
    { indicator_view_permission: 'indicator.view.permission' },
    { indicator_add_permission: 'indicator.add.permission' },
    { indicator_edit_permission: 'indicator.edit.permission' },
    { indicator_delete_permission: 'indicator.delete.permission' },
    { indicator_accept_permission: 'indicator.accept.permission' },
    { attributes_view_permission: 'attributes.view.permission' },
    { attributes_add_permission: 'attributes.add.permission' },
    { attributes_edit_permission: 'attributes.edit.permission' },
    { attributes_delete_permission: 'attributes.delete.permission' },
    { attributes_accept_permission: 'attributes.accept.permission' },
    { user_view_permission: 'user.view.permission' },
    { user_add_permission: 'user.add.permission' },
    { user_edit_permission: 'user.edit.permission' },
    { user_delete_permission: 'user.delete.permission' },
    { user_accept_permission: 'user.accept.permission' },
    { history_view_permission: 'history.view.permission' },
    { history_add_permission: 'history.add.permission' },
    { history_edit_permission: 'history.edit.permission' },
    { history_delete_permission: 'history.delete.permission' },
    { history_accept_permission: 'history.accept.permission' },
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_accept_permission: 'documents.accept.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  2: [
    { documents_view_permission: 'documents.view.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  3: [
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  4: [
    { indicatorcategory_view_permission: 'indicatorcategory.view.permission' },
    { indicatorcategory_add_permission: 'indicatorcategory.add.permission' },
    { indicatorcategory_edit_permission: 'indicatorcategory.edit.permission' },
    {
      indicatorcategory_delete_permission:
        'indicatorcategory.delete.permission',
    },

    { indicator_view_permission: 'indicator.view.permission' },
    { indicator_add_permission: 'indicator.add.permission' },
    { indicator_edit_permission: 'indicator.edit.permission' },
    { indicator_delete_permission: 'indicator.delete.permission' },
    { attributes_view_permission: 'attributes.view.permission' },
    { attributes_add_permission: 'attributes.add.permission' },
    { attributes_edit_permission: 'attributes.edit.permission' },
    { attributes_delete_permission: 'attributes.delete.permission' },
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  6: [
    { indicatorcategory_view_permission: 'indicatorcategory.view.permission' },
    { indicatorcategory_add_permission: 'indicatorcategory.add.permission' },
    { indicatorcategory_edit_permission: 'indicatorcategory.edit.permission' },
    {
      indicatorcategory_delete_permission:
        'indicatorcategory.delete.permission',
    },

    { indicator_view_permission: 'indicator.view.permission' },
    { indicator_add_permission: 'indicator.add.permission' },
    { indicator_edit_permission: 'indicator.edit.permission' },
    { indicator_delete_permission: 'indicator.delete.permission' },
    { attributes_view_permission: 'attributes.view.permission' },
    { attributes_add_permission: 'attributes.add.permission' },
    { attributes_edit_permission: 'attributes.edit.permission' },
    { attributes_delete_permission: 'attributes.delete.permission' },
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  7: [
    { indicatorcategory_view_permission: 'indicatorcategory.view.permission' },
    { indicatorcategory_add_permission: 'indicatorcategory.add.permission' },
    { indicatorcategory_edit_permission: 'indicatorcategory.edit.permission' },
    {
      indicatorcategory_delete_permission:
        'indicatorcategory.delete.permission',
    },

    { indicator_view_permission: 'indicator.view.permission' },
    { indicator_add_permission: 'indicator.add.permission' },
    { indicator_edit_permission: 'indicator.edit.permission' },
    { indicator_delete_permission: 'indicator.delete.permission' },
    { attributes_view_permission: 'attributes.view.permission' },
    { attributes_add_permission: 'attributes.add.permission' },
    { attributes_edit_permission: 'attributes.edit.permission' },
    { attributes_delete_permission: 'attributes.delete.permission' },
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
  8: [
    { indicatorcategory_view_permission: 'indicatorcategory.view.permission' },
    { indicatorcategory_add_permission: 'indicatorcategory.add.permission' },
    { indicatorcategory_edit_permission: 'indicatorcategory.edit.permission' },
    {
      indicatorcategory_delete_permission:
        'indicatorcategory.delete.permission',
    },

    { indicator_view_permission: 'indicator.view.permission' },
    { indicator_add_permission: 'indicator.add.permission' },
    { indicator_edit_permission: 'indicator.edit.permission' },
    { indicator_delete_permission: 'indicator.delete.permission' },
    { attributes_view_permission: 'attributes.view.permission' },
    { attributes_add_permission: 'attributes.add.permission' },
    { attributes_edit_permission: 'attributes.edit.permission' },
    { attributes_delete_permission: 'attributes.delete.permission' },
    { documents_view_permission: 'documents.view.permission' },
    { documents_upload_permission: 'documents.upload.permission' },
    { documents_edit_permission: 'documents.edit.permission' },
    { documents_delete_permission: 'documents.delete.permission' },
    { documents_download_permission: 'documents.download.permission' },
  ],
};
