spring:
  application:
    name: webgis
  datasource:
    url: jdbc:postgresql://localhost/postgis_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: SCHEMA_HISTORY
    locations:
      - classpath:/db/migration
      - classpath:/db/migration-data
    schemas: public

springdoc:
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: al.webgis.webgis.controller

server:
  port: 9000

geoserver:
  username: admin
  password: geoserver
  url: http://20.67.236.132:8080/geoserver



jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity: 3600000